using System;
using ShiftUI;
using System.Drawing;

namespace ShiftOS
{
    partial class Shifter
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {                components.Dispose();
            }
            base.Dispose(disposing);
        }

        public void InitializeComponent()
        {
            this.AllowTransparency = false;
            this.AutoScale = true;
            this.AutoScaleBaseSize = new Size(5, 13);
            this.AutoScroll = false;
            this.AutoSize = false;
            this.AutoSizeMode = AutoSizeMode.GrowOnly;
            this.AutoValidate = AutoValidate.Inherit;
            this.BackColor = Color.FromArgb(240, 240, 240);
            this.ClientSize = new Size(805, 463);
            this.WidgetBox = true;
            this.DesktopLocation = new Point(0, 0);
            this.DialogResult = DialogResult.None;
            this.FormBorderStyle = FormBorderStyle.Sizable;
            this.HelpButton = false;
            this.IsMdiContainer = false;
            this.KeyPreview = false;
            this.MaximizeBox = true;
            this.MaximumSize = new Size(0, 0);
            this.MinimizeBox = true;
            this.MinimumSize = new Size(0, 0);
            this.RightToLeftLayout = false;
            this.ShowIcon = true;
            this.ShowInTaskbar = true;
            this.Size = new Size(805, 463);
            this.SizeGripStyle = SizeGripStyle.Auto;
            this.StartPosition = FormStartPosition.WindowsDefaultLocation;
            this.TabIndex = 0;
            this.TabStop = true;
            this.TopLevel = true;
            this.TopMost = false;
            this.WindowState = FormWindowState.Normal;
            this.Text = "Shifter";
            this.Location = new Point(0, 0);
            this.AutoScaleMode = AutoScaleMode.Inherit;
            this.AutoScrollMargin = new Size(0, 0);
            this.AutoScrollMinSize = new Size(0, 0);
            this.AutoScrollPosition = new Point(0, 0);
            this.Alignment = (ContentAlignment)0;
            this.AccessibleDefaultActionDescription = "";
            this.AccessibleDescription = "";
            this.AccessibleName = "";
            this.AccessibleRole = AccessibleRole.Default;
            this.AllowDrop = false;
            this.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            this.AutoScrollOffset = new Point(0, 0);
            this.BackgroundImageLayout = ImageLayout.Tile;
            this.Capture = false;
            this.CausesValidation = true;
            this.Dock = DockStyle.None;
            this.Enabled = true;
            this.Font = new Font("Microsoft Sans Serif", (float)8.25, (FontStyle)0);
            this.ForeColor = Color.FromArgb(0, 0, 0);
            this.Height = 463;
            this.ImeMode = ImeMode.NoControl;
            this.IsAccessible = false;
            this.Left = 0;
            this.Name = "ShifterNew";
            this.RightToLeft = RightToLeft.No;
            this.Top = 0;
            this.UseWaitCursor = false;
            this.Visible = false;
            this.Width = 805;

            pgshifter = new PropertyGrid();
            pgshifter.AutoScroll = false;
            pgshifter.BackColor = Color.FromArgb(240, 240, 240);
            pgshifter.BackgroundImageLayout = ImageLayout.Tile;
            pgshifter.CategoryForeColor = Color.FromArgb(200, 200, 200);
            pgshifter.CommandsBackColor = Color.FromArgb(0, 0, 0);
            pgshifter.CommandsForeColor = Color.FromArgb(0, 0, 0);
            pgshifter.CommandsActiveLinkColor = Color.FromArgb(0, 0, 0);
            pgshifter.CommandsDisabledLinkColor = Color.FromArgb(0, 0, 0);
            pgshifter.CommandsLinkColor = Color.FromArgb(0, 0, 0);
            pgshifter.CommandsVisibleIfAvailable = false;
            pgshifter.ForeColor = Color.FromArgb(0, 0, 0);
            pgshifter.HelpBackColor = Color.FromArgb(240, 240, 240);
            pgshifter.HelpForeColor = Color.FromArgb(0, 0, 0);
            pgshifter.HelpVisible = true;
            pgshifter.LargeButtons = false;
            pgshifter.LineColor = Color.FromArgb(200, 200, 200);
            pgshifter.PropertySort = PropertySort.CategorizedAlphabetical;
            pgshifter.Text = "";
            pgshifter.ToolbarVisible = true;
            pgshifter.ViewBackColor = Color.FromArgb(255, 255, 255);
            pgshifter.ViewForeColor = Color.FromArgb(0, 0, 0);
            pgshifter.UseCompatibleTextRendering = false;
            pgshifter.AutoScaleMode = AutoScaleMode.Inherit;
            pgshifter.AutoValidate = AutoValidate.Inherit;
            pgshifter.AutoScrollMargin = new Size(0, 0);
            pgshifter.AutoScrollMinSize = new Size(0, 0);
            pgshifter.AutoScrollPosition = new Point(0, 0);
            pgshifter.Alignment = (ContentAlignment)0;
            pgshifter.AccessibleDefaultActionDescription = "";
            pgshifter.AccessibleDescription = "";
            pgshifter.AccessibleName = "";
            pgshifter.AccessibleRole = AccessibleRole.Default;
            pgshifter.AllowDrop = false;
            pgshifter.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pgshifter.AutoScrollOffset = new Point(0, 0);
            pgshifter.AutoSize = false;
            pgshifter.MaximumSize = new Size(0, 0);
            pgshifter.MinimumSize = new Size(0, 0);
            pgshifter.Capture = false;
            pgshifter.CausesValidation = true;
            pgshifter.ClientSize = new Size(504, 411);
            pgshifter.Dock = DockStyle.None;
            pgshifter.Enabled = true;
            pgshifter.Font = new Font("Microsoft Sans Serif", (float)8.25, (FontStyle)0);
            pgshifter.Height = 411;
            pgshifter.ImeMode = ImeMode.NoControl;
            pgshifter.IsAccessible = false;
            pgshifter.Left = 287;
            pgshifter.Location = new Point(287, 8);
            pgshifter.Name = "pgshifter";
            pgshifter.RightToLeft = RightToLeft.No;
            pgshifter.Size = new Size(504, 411 - (API.CurrentSkin.titlebarheight * 2));
            pgshifter.TabIndex = 0;
            pgshifter.TabStop = true;
            pgshifter.Top = 8;
            pgshifter.UseWaitCursor = false;
            pgshifter.Visible = true;
            pgshifter.Width = 504;
            this.Widgets.Add(pgshifter);
            pgshifter.Show();

            pnlcategoryholder = new Panel();
            pnlcategoryholder.AutoSize = false;
            pnlcategoryholder.AutoSizeMode = AutoSizeMode.GrowOnly;
            pnlcategoryholder.BorderStyle = BorderStyle.FixedSingle;
            pnlcategoryholder.TabStop = false;
            pnlcategoryholder.Text = "";
            pnlcategoryholder.AutoScroll = false;
            pnlcategoryholder.AutoScrollMargin = new Size(0, 0);
            pnlcategoryholder.AutoScrollMinSize = new Size(0, 0);
            pnlcategoryholder.AutoScrollPosition = new Point(0, 0);
            pnlcategoryholder.Alignment = (ContentAlignment)0;
            pnlcategoryholder.AccessibleDefaultActionDescription = "";
            pnlcategoryholder.AccessibleDescription = "";
            pnlcategoryholder.AccessibleName = "";
            pnlcategoryholder.AccessibleRole = AccessibleRole.Default;
            pnlcategoryholder.AllowDrop = false;
            pnlcategoryholder.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            pnlcategoryholder.AutoScrollOffset = new Point(0, 0);
            pnlcategoryholder.MaximumSize = new Size(0, 0);
            pnlcategoryholder.MinimumSize = new Size(0, 0);
            pnlcategoryholder.BackColor = Color.FromArgb(240, 240, 240);
            pnlcategoryholder.BackgroundImageLayout = ImageLayout.Tile;
            pnlcategoryholder.Capture = false;
            pnlcategoryholder.CausesValidation = true;
            pnlcategoryholder.Dock = DockStyle.None;
            pnlcategoryholder.Enabled = true;
            pnlcategoryholder.Font = new Font("Microsoft Sans Serif", (float)8.25, (FontStyle)0);
            pnlcategoryholder.ForeColor = Color.FromArgb(0, 0, 0);
            pnlcategoryholder.ImeMode = ImeMode.NoControl;
            pnlcategoryholder.IsAccessible = false;
            pnlcategoryholder.Left = 8;

            pnlcategoryholder.Location = new Point(8, 8);
            pnlcategoryholder.Name = "pnlcategories";
            pnlcategoryholder.RightToLeft = RightToLeft.No;
            pnlcategoryholder.Size = new Size(271, 409);
            pnlcategoryholder.Height = 409 - API.CurrentSkin.titlebarheight;
            pnlcategoryholder.TabIndex = 1;
            pnlcategoryholder.Top = 8 + API.CurrentSkin.titlebarheight;
            pnlcategoryholder.UseWaitCursor = false;
            pnlcategoryholder.Visible = true;
            pnlcategoryholder.Width = 271;
            this.Widgets.Add(pnlcategoryholder);
            pnlcategoryholder.Show();
            btnapply = new Button();
            btnapply.AutoSizeMode = AutoSizeMode.GrowOnly;
            btnapply.DialogResult = DialogResult.None;
            btnapply.AutoEllipsis = false;
            btnapply.AutoSize = false;
            btnapply.BackColor = Color.FromArgb(240, 240, 240);
            btnapply.FlatStyle = FlatStyle.Standard;
            btnapply.ImageAlign = ContentAlignment.MiddleCenter;
            btnapply.ImageIndex = -1;
            btnapply.ImageKey = "";
            btnapply.ImeMode = ImeMode.Disable;
            btnapply.Text = "Apply";
            btnapply.TextAlign = ContentAlignment.MiddleCenter;
            btnapply.TextImageRelation = TextImageRelation.Overlay;
            btnapply.UseCompatibleTextRendering = false;
            btnapply.UseMnemonic = true;
            btnapply.UseVisualStyleBackColor = true;
            btnapply.Alignment = (ContentAlignment)0;
            btnapply.AccessibleDefaultActionDescription = "";
            btnapply.AccessibleDescription = "";
            btnapply.AccessibleName = "";
            btnapply.AccessibleRole = AccessibleRole.Default;
            btnapply.AllowDrop = false;
            btnapply.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            btnapply.AutoScrollOffset = new Point(0, 0);
            btnapply.MaximumSize = new Size(0, 0);
            btnapply.MinimumSize = new Size(0, 0);
            btnapply.BackgroundImageLayout = ImageLayout.Tile;
            btnapply.Capture = false;
            btnapply.CausesValidation = true;
            btnapply.ClientSize = new Size(120, 36);
            btnapply.Dock = DockStyle.None;
            btnapply.Enabled = true;
            btnapply.Font = new Font("Microsoft Sans Serif", (float)12, (FontStyle)0);
            btnapply.ForeColor = Color.FromArgb(0, 0, 0);
            btnapply.Height = 36;
            btnapply.IsAccessible = false;
            btnapply.Left = 6;
            btnapply.Location = new Point(6, 365);
            btnapply.Name = "btnapply";
            btnapply.RightToLeft = RightToLeft.No;
            btnapply.Size = new Size(120, 36);
            btnapply.TabIndex = 0;
            btnapply.TabStop = true;
            btnapply.Top = 365;
            btnapply.UseWaitCursor = false;
            btnapply.Visible = true;
            btnapply.Width = 120;
            pnlcategoryholder.Widgets.Add(btnapply);
            btnapply.Show();
            pnlcategories = new FlowLayoutPanel();
            pnlcategories.FlowDirection = FlowDirection.TopDown;
            pnlcategories.WrapContents = true;
            pnlcategories.AutoSize = false;
            pnlcategories.AutoSizeMode = AutoSizeMode.GrowOnly;
            pnlcategories.BorderStyle = BorderStyle.FixedSingle;
            pnlcategories.TabStop = false;
            pnlcategories.Text = "";
            pnlcategories.AutoScroll = false;
            pnlcategories.AutoScrollMargin = new Size(0, 0);
            pnlcategories.AutoScrollMinSize = new Size(0, 0);
            pnlcategories.AutoScrollPosition = new Point(0, 0);
            pnlcategories.Alignment = (ContentAlignment)0;
            pnlcategories.AccessibleDefaultActionDescription = "";
            pnlcategories.AccessibleDescription = "";
            pnlcategories.AccessibleName = "";
            pnlcategories.AccessibleRole = AccessibleRole.Default;
            pnlcategories.AllowDrop = false;
            pnlcategories.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            pnlcategories.AutoScrollOffset = new Point(0, 0);
            pnlcategories.MaximumSize = new Size(0, 0);
            pnlcategories.MinimumSize = new Size(0, 0);
            pnlcategories.BackColor = Color.FromArgb(240, 240, 240);
            pnlcategories.BackgroundImageLayout = ImageLayout.Tile;
            pnlcategories.Capture = false;
            pnlcategories.CausesValidation = true;
            pnlcategories.ClientSize = new Size(121, 351);
            pnlcategories.Dock = DockStyle.None;
            pnlcategories.Enabled = true;
            pnlcategories.Font = new Font("Microsoft Sans Serif", (float)8.25, (FontStyle)0);
            pnlcategories.ForeColor = Color.FromArgb(0, 0, 0);
            pnlcategories.Height = 353;
            pnlcategories.ImeMode = ImeMode.NoControl;
            pnlcategories.IsAccessible = false;
            pnlcategories.Left = 6;
            pnlcategories.Location = new Point(6, 6);
            pnlcategories.Name = "pnlcategories";
            pnlcategories.RightToLeft = RightToLeft.No;
            pnlcategories.Size = new Size(123, 353);
            pnlcategories.TabIndex = 1;
            pnlcategories.Top = 6;
            pnlcategories.UseWaitCursor = false;
            pnlcategories.Visible = true;
            pnlcategories.Width = 123;
            pnlcategoryholder.Widgets.Add(pnlcategories);
            pnlcategories.Show();
            pnlsubcategories = new FlowLayoutPanel();
            pnlsubcategories.FlowDirection = FlowDirection.TopDown;
            pnlsubcategories.WrapContents = true;
            pnlsubcategories.AutoSize = false;
            pnlsubcategories.AutoSizeMode = AutoSizeMode.GrowOnly;
            pnlsubcategories.BorderStyle = BorderStyle.None;
            pnlsubcategories.TabStop = false;
            pnlsubcategories.Text = "";
            pnlsubcategories.AutoScroll = false;
            pnlsubcategories.AutoScrollMargin = new Size(0, 0);
            pnlsubcategories.AutoScrollMinSize = new Size(0, 0);
            pnlsubcategories.AutoScrollPosition = new Point(0, 0);
            pnlsubcategories.Alignment = (ContentAlignment)0;
            pnlsubcategories.AccessibleDefaultActionDescription = "";
            pnlsubcategories.AccessibleDescription = "";
            pnlsubcategories.AccessibleName = "";
            pnlsubcategories.AccessibleRole = AccessibleRole.Default;
            pnlsubcategories.AllowDrop = false;
            pnlsubcategories.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            pnlsubcategories.AutoScrollOffset = new Point(0, 0);
            pnlsubcategories.MaximumSize = new Size(0, 0);
            pnlsubcategories.MinimumSize = new Size(0, 0);
            pnlsubcategories.BackColor = Color.FromArgb(240, 240, 240);
            pnlsubcategories.BackgroundImageLayout = ImageLayout.Tile;
            pnlsubcategories.Capture = false;
            pnlsubcategories.CausesValidation = true;
            pnlsubcategories.ClientSize = new Size(124, 394);
            pnlsubcategories.Dock = DockStyle.None;
            pnlsubcategories.Enabled = true;
            pnlsubcategories.Font = new Font("Microsoft Sans Serif", (float)8.25, (FontStyle)0);
            pnlsubcategories.ForeColor = Color.FromArgb(0, 0, 0);
            pnlsubcategories.Height = 394;
            pnlsubcategories.ImeMode = ImeMode.NoControl;
            pnlsubcategories.IsAccessible = false;
            pnlsubcategories.Left = 135;
            pnlsubcategories.Location = new Point(135, 6);
            pnlsubcategories.Name = "pnlsubcategories";
            pnlsubcategories.RightToLeft = RightToLeft.No;
            pnlsubcategories.Size = new Size(124, 394);
            pnlsubcategories.TabIndex = 2;
            pnlsubcategories.Top = 6;
            pnlsubcategories.UseWaitCursor = false;
            pnlsubcategories.Visible = true;
            pnlsubcategories.Width = 124;
            pnlcategories.Widgets.Add(pnlsubcategories);
            pnlsubcategories.Show();

        }
        public PropertyGrid pgshifter = null;
        public Panel pnlcategoryholder = null;
        public Button btnapply = null;
        public FlowLayoutPanel pnlcategories = null;
        public FlowLayoutPanel pnlsubcategories = null;


    }
}