// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer.
//     http://toolstripcustomizer.codeplex.com/
// </auto-generated>

using System.Drawing;
using ShiftUI;

namespace ShiftOS
{
    class ShiftOSColorTable : ProfessionalColorTable
    {
        public override Color ButtonSelectedHighlight
        {
            get { return API.CurrentSkin.Menu_ButtonSelectedHighlight; }
        }
        public override Color ButtonSelectedHighlightBorder
        {
            get { return API.CurrentSkin.Menu_ButtonSelectedHighlight; }
        }
        public override Color ButtonPressedHighlight
        {
            get { return API.CurrentSkin.Menu_ButtonPressedHighlight; }
        }
        public override Color ButtonPressedHighlightBorder
        {
            get { return API.CurrentSkin.Menu_ButtonPressedHighlight; }
        }
        public override Color ButtonCheckedHighlight
        {
            get { return API.CurrentSkin.Menu_ButtonCheckedHighlight; }
        }
        public override Color ButtonCheckedHighlightBorder
        {
            get { return API.CurrentSkin.Menu_ButtonCheckedHighlightBorder; }
        }
        public override Color ButtonPressedBorder
        {
            get { return API.CurrentSkin.Menu_ButtonPressedBorder; }
        }
        public override Color ButtonSelectedBorder
        { 
            get { return API.CurrentSkin.Menu_ButtonSelectedBorder; }
        }
        public override Color ButtonCheckedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ButtonCheckedGradientBegin; }
        }
        public override Color ButtonCheckedGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ButtonCheckedGradientMiddle; }
        }
        public override Color ButtonCheckedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ButtonCheckedGradientEnd; }
        }
        public override Color ButtonSelectedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ButtonSelectedGradientBegin; }
        }
        public override Color ButtonSelectedGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ButtonSelectedGradientMiddle; }
        }
        public override Color ButtonSelectedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ButtonSelectedGradientEnd; }
        }
        public override Color ButtonPressedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ButtonPressedGradientBegin; }
        }
        public override Color ButtonPressedGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ButtonPressedGradientMiddle; }
        }
        public override Color ButtonPressedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ButtonPressedGradientEnd; }
        }
        public override Color CheckBackground
        { 
            get { return API.CurrentSkin.Menu_CheckBackground; }
        }
        public override Color CheckSelectedBackground
        { 
            get { return API.CurrentSkin.Menu_CheckSelectedBackground; }
        }
        public override Color CheckPressedBackground
        { 
            get { return API.CurrentSkin.Menu_CheckPressedBackground; }
        }
        public override Color GripDark
        { 
            get { return Color.Transparent; }
        }
        public override Color GripLight
        { 
            get { return Color.Transparent; }
        }
        public override Color ImageMarginGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientBegin; }
        }
        public override Color ImageMarginGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientMiddle; }
        }
        public override Color ImageMarginGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientEnd; }
        }
        public override Color ImageMarginRevealedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientBegin; }
        }
        public override Color ImageMarginRevealedGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientMiddle; }
        }
        public override Color ImageMarginRevealedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ImageMarginGradientEnd; }
        }
        public override Color MenuStripGradientBegin
        { 
            get { return API.CurrentSkin.Menu_MenuStripGradientBegin; }
        }
        public override Color MenuStripGradientEnd
        { 
            get { return API.CurrentSkin.Menu_MenuStripGradientEnd; }
        }
        public override Color MenuItemSelected
        { 
            get { return API.CurrentSkin.Menu_MenuItemSelected; }
        }
        public override Color MenuItemBorder
        { 
            get { return API.CurrentSkin.Menu_MenuItemSelected; }
        }
        public override Color MenuBorder
        { 
            get { return API.CurrentSkin.Menu_MenuBorder; }
        }
        public override Color MenuItemSelectedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_MenuItemSelectedGradientBegin; }
        }
        public override Color MenuItemSelectedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_MenuItemSelectedGradientEnd; }
        }
        public override Color MenuItemPressedGradientBegin
        { 
            get { return API.CurrentSkin.Menu_MenuItemPressedGradientBegin; }
        }
        public override Color MenuItemPressedGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_MenuItemPressedGradientMiddle; }
        }
        public override Color MenuItemPressedGradientEnd
        { 
            get { return API.CurrentSkin.Menu_MenuItemPressedGradientEnd; }
        }
        public override Color RaftingContainerGradientBegin
        { 
            get { return API.CurrentSkin.Menu_RaftingContainerGradientBegin; }
        }
        public override Color RaftingContainerGradientEnd
        { 
            get { return API.CurrentSkin.Menu_RaftingContainerGradientEnd; }
        }
        public override Color SeparatorDark
        { 
            get { return API.CurrentSkin.Menu_SeparatorDark; }
        }
        public override Color SeparatorLight
        { 
            get { return API.CurrentSkin.Menu_SeparatorLight; }
        }
        public override Color StatusStripGradientBegin
        { 
            get { return API.CurrentSkin.Menu_StatusStripGradientBegin; }
        }
        public override Color StatusStripGradientEnd
        { 
            get { return API.CurrentSkin.Menu_StatusStripGradientEnd; }
        }
        public override Color ToolStripBorder
        { 
            get { return API.CurrentSkin.Menu_ToolStripBorder; }
        }
        public override Color ToolStripDropDownBackground
        { 
            get { return API.CurrentSkin.Menu_ToolStripDropDownBackground; }
        }
        public override Color ToolStripGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ToolStripGradientBegin; }
        }
        public override Color ToolStripGradientMiddle
        { 
            get { return API.CurrentSkin.Menu_ToolStripGradientMiddle; }
        }
        public override Color ToolStripGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ToolStripGradientEnd; }
        }
        public override Color ToolStripContentPanelGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ToolStripContentPanelGradientBegin; }
        }
        public override Color ToolStripContentPanelGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ToolStripContentPanelGradientEnd; }
        }
        public override Color ToolStripPanelGradientBegin
        { 
            get { return API.CurrentSkin.Menu_ToolStripPanelGradientBegin; }
        }
        public override Color ToolStripPanelGradientEnd
        { 
            get { return API.CurrentSkin.Menu_ToolStripPanelGradientEnd; }
        }
        public override Color OverflowButtonGradientBegin
        { 
            get { return Color.Transparent; }
        }
        public override Color OverflowButtonGradientMiddle
        { 
            get { return Color.Transparent; }
        }
        public override Color OverflowButtonGradientEnd
        { 
            get { return Color.Transparent; }
        }
    }
}